#  6: Binary Logistic Regression

See 6.2.2 - Fitting the Model in R <https://online.stat.psu.edu/stat504/lesson/6/6.2/6.2.2>

In [27]:
import numpy as np
import pandas as pd
import statsmodels.api as sm

x = np.random.choice(2, 100)
y = np.random.choice(2, 100)

df = pd.DataFrame.from_records(zip(x,y), columns=["X", "Y"])

df


/home/romulus/.local/lib/python3.10/site-packages/statsmodels/compat/pandas.py:65: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import Int64Index as NumericIndex


X  Y
0   1  1
1   0  1
2   0  0
3   0  1
4   1  1
.. .. ..
95  1  0
96  1  1
97  0  1
98  1  1
99  1  0

[100 rows x 2 columns]

In [28]:
df.groupby(["X","Y"]).size().unstack()

Y   0   1
X        
0  23  27
1  21  29

In [38]:
# https://realpython.com/logistic-regression-python/

x = np.arange(10).reshape(-1, 1)
y = np.array([0, 1, 0, 0, 1, 1, 1, 1, 1, 1])
x = sm.add_constant(x)

x,y

(array([[1., 0.],
        [1., 1.],
        [1., 2.],
        [1., 3.],
        [1., 4.],
        [1., 5.],
        [1., 6.],
        [1., 7.],
        [1., 8.],
        [1., 9.]]),
 array([0, 1, 0, 0, 1, 1, 1, 1, 1, 1]))

In [39]:
model = sm.Logit(y, x)
result = model.fit(method='newton')

Optimization terminated successfully.
         Current function value: 0.350471
         Iterations 7


In [45]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                      y   No. Observations:                   10
Model:                          Logit   Df Residuals:                        8
Method:                           MLE   Df Model:                            1
Date:                Thu, 10 Mar 2022   Pseudo R-squ.:                  0.4263
Time:                        17:16:13   Log-Likelihood:                -3.5047
converged:                       True   LL-Null:                       -6.1086
Covariance Type:            nonrobust   LLR p-value:                   0.02248
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -1.9728      1.737     -1.136      0.256      -5.377       1.431
x1             0.8224      0.528      1.557      0.119      -0.213       1.858
==============================================================================
"""

In [ ]:
result.summary2()

In [46]:
(result.predict(x) >= 0.5).astype(int)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1])

In [47]:
result.pred_table()

array([[2., 1.],
       [1., 6.]])